### PR TITLE
Standard response exception

### PR DESCRIPTION
**Pull request by TSchuermans**
Added a response exception which corresponds to the JSON-RPC 2.0 spec error object.

http://www.jsonrpc.org/specification#error_object

### CODE REVIEW

**Comment by jonaswouters** [comment]
+1

**Comment by TSchuermans** [comment]
@fguillot mind reviewing? :)

**Comment by fguillot** [comment]
Why you aren't using the existing feature? https://github.com/fguillot/JsonRPC#exceptions  https://github.com/fguillot/JsonRPC/blob/master/src/JsonRPC/Server.php#L466-L480

**Comment by TSchuermans** [comment]
Because the data property isn't present in the default exceptions?
I could make the response exception abstract and have the other exceptions extend it if that's better?

**Comment by fguillot** [comment]
It's merged, sorry about the delay.

**Pull request merged**
