### PR TITLE
Client: handle http redirects

### PR DESCRIPTION
**Pull request by chorry**
Detects 30x code in response, follows proposed location and updates request url with new data.

### CODE REVIEW

**Comment by maxnet** [comment]
Maybe have a redirect limit, to protect against buggy server that redirects to itself in loop?

**Comment by fguillot** [comment]
By default, stream context are supposed to follow the location: http://php.net/manual/en/context.http.php#context.http.follow-location and the current implementation already impose a max redirect: https://github.com/fguillot/JsonRPC/blob/master/src/JsonRPC/Client.php#L345

**Comment by chorry** [comment]
"Follow-location" is available only since 5.3.4, while this lib has "PHP >= 5.3" requirements
Maybe update min-req then?

**Comment by fguillot** [comment]
I changed the requirements to PHP 5.3.4.

**Pull request closed without merging**
