### PR TITLE
Add options for json_encode function

### PR DESCRIPTION
**Pull request by 0x2e**

### CODE REVIEW

**Comment by fguillot** [comment]
What problem are you trying to solve? where is the unit test?

**Comment by 0x2e** [comment]
just make the json data esay to read.
```
json_encode('中国') --> "\u4e2d\u56fd"
json_encode('中国', JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) --> "中国"
```
some libraries (eg. `monolog/monolog`, `symfony/console`) use this as default options.
if you don't think this is a big problem, please create a new tag from the master branch, then I can overwrite the `ResponseBuilder::build` method.
there is no need to create an unit test for this change.

**Comment by 0x2e** [comment]
please reject this pull request if you don't accept. :)

**Comment by fguillot** [comment]
It's ok if that doesn't introduce any breaking changes.

**Comment by 0x2e** [comment]
thanks

**Pull request merged**
